# Spdlog package configuration
PKG_NAME:=spdlog
PKG_VERSION:=0.16.3
PKG_RELEASE:=$(PKG_SOURCE_VERSION)
PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/gabime/spdlog.git
PKG_SOURCE_SUBDIR:=${PKG_NAME}-${PKG_VERSION}
PKG_SOURCE_VERSION:=ccd675a286f457068ee8c823f8207f13c2325b26
PKG_SOURCE:=${PKG_NAME}-${PKG_SOURCE_VERSION}.tar.gz
