PKG_NAME:=protobuf
PKG_VERSION:=3.2.0
PKG_RELEASE:=1

PKG_SOURCE:=$(PKG_NAME)-cpp-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://github.com/google/protobuf/releases/download/v$(PKG_VERSION)
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
PKG_MD5SUM:=46ab34b63ac77c02d4351961f6f85ded

PKG_LICENSE:=BSD-3-Clause
PKG_LICENSE_FILES:=LICENSE
